###############################################################################
# Created by write_sdc
# Sat Aug 15 03:08:03 2026
###############################################################################
current_design design_mux
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name SCK -period 10.0000 [get_ports {SCK}]
set_clock_transition 0.1500 [get_clocks {SCK}]
set_clock_uncertainty 0.2500 SCK
set_propagated_clock [get_clocks {SCK}]
set_input_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {CSB}]
set_input_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {RST}]
set_input_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {SDI}]
set_input_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {VDD}]
set_input_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {VSS}]
set_input_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {mask_rev_in[0]}]
set_input_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {mask_rev_in[1]}]
set_input_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {mask_rev_in[2]}]
set_input_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {mask_rev_in[3]}]
set_input_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {trap}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {SDO}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {VDD}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {VSS}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {irq}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {mask_rev[0]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {mask_rev[1]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {mask_rev[2]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {mask_rev[3]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {mfgr_id[0]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {mfgr_id[10]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {mfgr_id[11]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {mfgr_id[1]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {mfgr_id[2]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {mfgr_id[3]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {mfgr_id[4]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {mfgr_id[5]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {mfgr_id[6]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {mfgr_id[7]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {mfgr_id[8]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {mfgr_id[9]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {out}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {pll_bias_ena}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {pll_bypass}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {pll_cp_ena}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {pll_trim[0]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {pll_trim[1]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {pll_trim[2]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {pll_trim[3]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {pll_vco_ena}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {prod_id[0]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {prod_id[1]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {prod_id[2]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {prod_id[3]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {prod_id[4]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {prod_id[5]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {prod_id[6]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {prod_id[7]}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {reg_ena}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {sdo_enb}]
set_output_delay 2.0000 -clock [get_clocks {SCK}] -add_delay [get_ports {xtal_ena}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {SDO}]
set_load -pin_load 0.0334 [get_ports {VDD}]
set_load -pin_load 0.0334 [get_ports {VSS}]
set_load -pin_load 0.0334 [get_ports {irq}]
set_load -pin_load 0.0334 [get_ports {out}]
set_load -pin_load 0.0334 [get_ports {pll_bias_ena}]
set_load -pin_load 0.0334 [get_ports {pll_bypass}]
set_load -pin_load 0.0334 [get_ports {pll_cp_ena}]
set_load -pin_load 0.0334 [get_ports {pll_vco_ena}]
set_load -pin_load 0.0334 [get_ports {reg_ena}]
set_load -pin_load 0.0334 [get_ports {sdo_enb}]
set_load -pin_load 0.0334 [get_ports {xtal_ena}]
set_load -pin_load 0.0334 [get_ports {mask_rev[3]}]
set_load -pin_load 0.0334 [get_ports {mask_rev[2]}]
set_load -pin_load 0.0334 [get_ports {mask_rev[1]}]
set_load -pin_load 0.0334 [get_ports {mask_rev[0]}]
set_load -pin_load 0.0334 [get_ports {mfgr_id[11]}]
set_load -pin_load 0.0334 [get_ports {mfgr_id[10]}]
set_load -pin_load 0.0334 [get_ports {mfgr_id[9]}]
set_load -pin_load 0.0334 [get_ports {mfgr_id[8]}]
set_load -pin_load 0.0334 [get_ports {mfgr_id[7]}]
set_load -pin_load 0.0334 [get_ports {mfgr_id[6]}]
set_load -pin_load 0.0334 [get_ports {mfgr_id[5]}]
set_load -pin_load 0.0334 [get_ports {mfgr_id[4]}]
set_load -pin_load 0.0334 [get_ports {mfgr_id[3]}]
set_load -pin_load 0.0334 [get_ports {mfgr_id[2]}]
set_load -pin_load 0.0334 [get_ports {mfgr_id[1]}]
set_load -pin_load 0.0334 [get_ports {mfgr_id[0]}]
set_load -pin_load 0.0334 [get_ports {pll_trim[3]}]
set_load -pin_load 0.0334 [get_ports {pll_trim[2]}]
set_load -pin_load 0.0334 [get_ports {pll_trim[1]}]
set_load -pin_load 0.0334 [get_ports {pll_trim[0]}]
set_load -pin_load 0.0334 [get_ports {prod_id[7]}]
set_load -pin_load 0.0334 [get_ports {prod_id[6]}]
set_load -pin_load 0.0334 [get_ports {prod_id[5]}]
set_load -pin_load 0.0334 [get_ports {prod_id[4]}]
set_load -pin_load 0.0334 [get_ports {prod_id[3]}]
set_load -pin_load 0.0334 [get_ports {prod_id[2]}]
set_load -pin_load 0.0334 [get_ports {prod_id[1]}]
set_load -pin_load 0.0334 [get_ports {prod_id[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {CSB}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {RST}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SCK}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SDI}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {VDD}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {VSS}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {trap}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mask_rev_in[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mask_rev_in[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mask_rev_in[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {mask_rev_in[0]}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_transition 0.7500 [current_design]
set_max_fanout 10.0000 [current_design]
